name: "Run Docs CD"

on:
  push:
    branches:
      - "docs-ko"

jobs:
  build-deploy-docs:
    uses: ./.github/workflows/docs.yml
    with:
      deploy: true
    permissions:
      contents: write
